on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v1.10
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing scribble-code-examples and its dependencies
        run: raco pkg install --no-docs --auto ./scribble-code-examples-lib ./scribble-code-examples
      - name: Compiling scribble-code-examples and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps scribble-code-examples
      - name: Testing scribble-code-examples
        run: raco test -p scribble-code-examples-lib scribble-code-examples
